# Generated by Django 3.2.3 on 2021-05-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210527_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
